name: Copy branches main to documentation 


# Controls when the action will run.
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [main]

    # inputs: TODO put variables in here for easier to config, see https://stackoverflow.com/questions/74072206
# env: this didn't work, see below for input
  # GITHUB_USER: hannesdelbeke
  # GITHUB_REPO: notes
  # BRANCH_SOURCE: main
  # BRANCH_PUBLISH: documentation

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
jobs:
  copy-images:
    runs-on: ubuntu-latest
    steps:
      # - name: prepare input
      #   # All steps after this one will have env variable `GHA_BRANCH` passed to them.
      #   run:   echo ::set-env name=GHA_BRANCH::$(echo $GITHUB_REF | awk -F / '{print $3}')
      #   shell: bash
      #   # see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # TODO run janitor on markdown input
      
      # TODO garantuee image and note folder exists
      # - name: setup copy
      #   run: mkdir -p 

      - name: Copy Images
        uses: andstor/copycat-action@v3.2.4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN  }}
          src_branch: main
          src_path: /notes/image/.
          dst_owner: hannesdelbeke
          dst_repo_name: ${{ github.event.repository.name }}
          dst_path: /static/images/
          dst_branch: mkdocs
          clean: true  # empty dst_path before copying
          commit_message: "Images copied from main to documentation branch!"

  copy-sections:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy Markdowns
        uses: andstor/copycat-action@v3.2.4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN  }}
          src_branch: main
          src_path: /notes/.
          dst_owner: hannesdelbeke
          dst_repo_name: ${{ github.event.repository.name }}
          dst_path: /docs/
          dst_branch: mkdocs
          clean: true  # empty dst_path before copying
          commit_message: "Sections copied from main to documentation branch!"
          
# copy-readme:
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v2
#     - name: Copy Markdowns
#       uses: andstor/copycat-action@v3
#       with:
#         personal_token: ${{ secrets.PERSONAL_TOKEN  }}
#         src_branch: main
#         src_path: /README.md
#         dst_owner: andkret
#         dst_repo_name: ${{ github.event.repository.name }}
#         dst_path: /docs/
#         dst_branch: mkdocs
#         commit_message: "README.md copied from main to documentation branch!"